Repository microsoft/build-server-for-gradle, pull requests merged in 2024-06, with the labels that each got.

#153 fix - Only send build target count during initialization
  server/src/main/java/com/microsoft/java/bs/core/internal/services/BuildTargetService.java
Labels: engineering

#149 Handle older versions of Gradle
  plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/ScalaLanguageModelBuilder.java
  plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/SourceSetsModelBuilder.java
  plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/dependency/DependencyCollector.java
  plugin/src/test/java/com/microsoft/java/bs/gradle/plugin/GradleBuildServerPluginTest.java
  testProjects/infer-source-roots/build.gradle
  testProjects/junit5-jupiter-starter-gradle/build.gradle
  testProjects/non-java/settings.gradle
  testProjects/scala-2/build.gradle
  testProjects/scala-3/build.gradle
Labels: bug, engineering

#152 fix - Add JDK 22 compatibility support
  server/src/main/java/com/microsoft/java/bs/core/internal/gradle/Utils.java
  server/src/test/java/com/microsoft/java/bs/core/internal/gradle/UtilsTest.java
Labels: bug

#156 Return the root cause of the message
  server/src/main/java/com/microsoft/java/bs/core/internal/server/GradleBuildServer.java
Labels: engineering
