Repository microsoft/build-server-for-gradle, pull requests merged in 2024-09, with the labels that each got.

#173 Android Java Project Support
  model/src/main/java/com/microsoft/java/bs/gradle/model/GradleSourceSet.java
  model/src/main/java/com/microsoft/java/bs/gradle/model/actions/GetSourceSetsAction.java
  model/src/main/java/com/microsoft/java/bs/gradle/model/impl/DefaultGradleSourceSet.java
  plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/SourceSetsModelBuilder.java
  plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/dependency/AndroidDependencyCollector.java
  plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/dependency/DependencyCollector.java
  plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/utils/AndroidUtils.java
  plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/utils/SourceSetUtils.java
  plugin/src/test/java/com/microsoft/java/bs/gradle/plugin/GradleBuildServerPluginTest.java
  server/src/main/java/com/microsoft/java/bs/core/internal/services/BuildTargetService.java
  server/src/test/java/com/microsoft/java/bs/core/internal/gradle/GradleApiConnectorTest.java
  server/src/test/java/com/microsoft/java/bs/core/internal/server/BuildTargetServiceIntegrationTest.java
  server/src/test/java/com/microsoft/java/bs/core/internal/services/BuildTargetServiceTest.java
  testProjects/android-test/.gitignore
  testProjects/android-test/app/.gitignore
  testProjects/android-test/app/build.gradle
  testProjects/android-test/app/src/androidTest/java/com/example/androidtest/ExampleInstrumentedTest.java
  testProjects/android-test/app/src/main/AndroidManifest.xml
  testProjects/android-test/app/src/main/java/com/example/androidtest/MainActivity.java
  testProjects/android-test/app/src/main/res/layout/activity_main.xml
  testProjects/android-test/app/src/test/java/com/example/androidtest/ExampleUnitTest.java
  testProjects/android-test/build.gradle
  testProjects/android-test/gradle.properties
  testProjects/android-test/gradle/libs.versions.toml
  testProjects/android-test/gradle/wrapper/gradle-wrapper.properties
  testProjects/android-test/gradlew
  testProjects/android-test/gradlew.bat
  testProjects/android-test/mylibrary/.gitignore
  testProjects/android-test/mylibrary/build.gradle
  testProjects/android-test/mylibrary/src/androidTest/java/com/example/mylibrary/ExampleInstrumentedTest.java
  testProjects/android-test/mylibrary/src/main/AndroidManifest.xml
  testProjects/android-test/mylibrary/src/main/java/com/example/mylibrary/Greeting.java
  testProjects/android-test/mylibrary/src/test/java/com/example/mylibrary/ExampleUnitTest.java
  testProjects/android-test/settings.gradle
Labels: enhancement, android

#186 build - Add project version information
  .azure-pipelines/rc.yml
  README.md
  gradle.properties
  plugin/build.gradle
  plugin/src/test/java/com/microsoft/java/bs/gradle/plugin/PluginHelper.java
  server/build.gradle
  server/src/main/java/com/microsoft/java/bs/core/Constants.java
Labels: bug

#189 Developer Documentation
  CONTRIBUTING.md
  README.md
  docs/android/README.md
  docs/developer.md
  docs/images/android_build_process.png
  docs/images/composite_build.png
  docs/images/java_home_handling.png
  docs/images/sourceset_build_logic.png
Labels: documentation
