Repository microsoft/build-server-for-gradle, pull requests merged in 2024-07, with the labels that each got.

#144 Add support for running tests
  README.md
  plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/SourceSetsModelBuilder.java
  server/build.gradle
  server/src/main/java/ch/epfl/scala/bsp4j/extended/TestFinishEx.java
  server/src/main/java/ch/epfl/scala/bsp4j/extended/TestName.java
  server/src/main/java/ch/epfl/scala/bsp4j/extended/TestStartEx.java
  server/src/main/java/com/microsoft/java/bs/core/internal/gradle/GradleApiConnector.java
  server/src/main/java/com/microsoft/java/bs/core/internal/gradle/Utils.java
  server/src/main/java/com/microsoft/java/bs/core/internal/managers/BuildTargetManager.java
  server/src/main/java/com/microsoft/java/bs/core/internal/reporter/CompileProgressReporter.java
  server/src/main/java/com/microsoft/java/bs/core/internal/reporter/TestReportReporter.java
  server/src/main/java/com/microsoft/java/bs/core/internal/server/GradleBuildServer.java
  server/src/main/java/com/microsoft/java/bs/core/internal/services/BuildTargetService.java
  server/src/test/java/com/microsoft/java/bs/core/internal/gradle/GradleApiConnectorTest.java
  server/src/test/java/com/microsoft/java/bs/core/internal/server/BuildTargetServerIntegrationTest.java
  testProjects/java-tests/build.gradle
  testProjects/java-tests/settings.gradle
  testProjects/java-tests/src/extraTest/java/com/example/project/ExtraTests.java
  testProjects/java-tests/src/main/java/com/example/project/Empty.java
  testProjects/java-tests/src/test/java/com/example/project/EnvVarTests.java
  testProjects/java-tests/src/test/java/com/example/project/ExceptionInBefore.java
  testProjects/java-tests/src/test/java/com/example/project/FailingTests.java
  testProjects/java-tests/src/test/java/com/example/project/NestedTests.java
  testProjects/java-tests/src/test/java/com/example/project/PassingTests.java
  testProjects/java-tests/src/test/java/com/example/project/TestFactoryTests.java
  testProjects/spock/build.gradle
  testProjects/spock/settings.gradle
  testProjects/spock/src/test/groovy/com/example/project/SpockTest.groovy
  testProjects/testng/build.gradle
  testProjects/testng/settings.gradle
  testProjects/testng/src/test/java/com/example/project/EnvVarTests.java
  testProjects/testng/src/test/java/com/example/project/ExceptionInBefore.java
  testProjects/testng/src/test/java/com/example/project/FailingTests.java
  testProjects/testng/src/test/java/com/example/project/PassingTests.java
Labels: enhancement

#160 LanguageExtension downcast resolution
  model/src/main/java/com/microsoft/java/bs/gradle/model/LanguageExtension.java
  model/src/main/java/com/microsoft/java/bs/gradle/model/impl/DefaultGradleSourceSet.java
  model/src/main/java/com/microsoft/java/bs/gradle/model/impl/DefaultJavaExtension.java
  model/src/main/java/com/microsoft/java/bs/gradle/model/impl/DefaultJavaLanguage.java
  model/src/main/java/com/microsoft/java/bs/gradle/model/impl/DefaultScalaExtension.java
  model/src/main/java/com/microsoft/java/bs/gradle/model/impl/DefaultScalaLanguage.java
  server/src/test/java/com/microsoft/java/bs/core/internal/managers/BuildTargetManagerTest.java
  server/src/test/java/com/microsoft/java/bs/core/internal/services/BuildTargetServiceTest.java
Labels: engineering

#164 Set env vars for Windows testing
  server/src/main/java/com/microsoft/java/bs/core/internal/gradle/GradleApiConnector.java
  server/src/test/java/com/microsoft/java/bs/core/internal/server/BuildTargetServerIntegrationTest.java
Labels: bug

#154 Composite Builds using Build Actions
  model/src/main/java/com/microsoft/java/bs/gradle/model/GradleSourceSets.java
  model/src/main/java/com/microsoft/java/bs/gradle/model/GradleSourceSetsMetadata.java
  model/src/main/java/com/microsoft/java/bs/gradle/model/impl/DefaultGradleSourceSets.java
  model/src/main/java/com/microsoft/java/bs/gradle/model/impl/DefaultGradleSourceSetsMetadata.java
  plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/SourceSetsModelBuilder.java
  plugin/src/test/java/com/microsoft/java/bs/gradle/plugin/GradleBuildServerPluginTest.java
  server/src/main/java/com/microsoft/java/bs/core/internal/gradle/GradleApiConnector.java
  server/src/main/java/com/microsoft/java/bs/core/internal/gradle/actions/GetSourceSetsAction.java
  server/src/test/java/com/microsoft/java/bs/core/internal/gradle/GradleApiConnectorTest.java
  testProjects/composite-build-1/build.gradle
  testProjects/composite-build-1/projectA/build.gradle
  testProjects/composite-build-1/projectA/settings.gradle
  testProjects/composite-build-1/projectB/build.gradle
  testProjects/composite-build-1/projectB/settings.gradle
  testProjects/composite-build-1/settings.gradle
  testProjects/composite-build-2/build.gradle
  testProjects/composite-build-2/my-app/app/build.gradle
  testProjects/composite-build-2/my-app/app/src/main/java/org/sample/myapp/Main.java
  testProjects/composite-build-2/my-app/settings.gradle
  testProjects/composite-build-2/my-utils/number-utils/build.gradle
  testProjects/composite-build-2/my-utils/number-utils/src/main/java/org/sample/numberutils/Numbers.java
  testProjects/composite-build-2/my-utils/settings.gradle
  testProjects/composite-build-2/my-utils/string-utils/build.gradle
  testProjects/composite-build-2/my-utils/string-utils/src/main/java/org/sample/stringutils/Strings.java
  testProjects/composite-build-2/settings.gradle
Labels: bug

#166 fix - Cannot get test display name
  server/src/main/java/com/microsoft/java/bs/core/internal/reporter/TestReportReporter.java
Labels: bug

#170 fix - Unsupported class file for the build action class
  model/build.gradle
  model/src/main/java/com/microsoft/java/bs/gradle/model/actions/GetSourceSetsAction.java
  plugin/build.gradle
  plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/SourceSetsModelBuilder.java
  server/build.gradle
  server/src/main/java/com/microsoft/java/bs/core/internal/gradle/GradleApiConnector.java
  server/src/main/java/com/microsoft/java/bs/core/internal/gradle/Utils.java
Labels: bug

#171 fix - Use project dir instead of project path
  model/src/main/java/com/microsoft/java/bs/gradle/model/BuildTargetDependency.java
  model/src/main/java/com/microsoft/java/bs/gradle/model/impl/DefaultBuildTargetDependency.java
  plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/SourceSetsModelBuilder.java
  server/src/main/java/com/microsoft/java/bs/core/internal/managers/BuildTargetManager.java
  server/src/test/java/com/microsoft/java/bs/core/internal/gradle/GradleApiConnectorTest.java
  server/src/test/java/com/microsoft/java/bs/core/internal/managers/BuildTargetManagerTest.java
Labels: bug

#172 fix - --no-daemon not working on Gradle 8.9
  server/src/main/java/com/microsoft/java/bs/core/internal/gradle/GradleApiConnector.java
Labels: bug

#174 build - Prepare for 0.3.0
  CHANGELOG.md
  server/src/main/java/com/microsoft/java/bs/core/Constants.java
Labels: engineering

#162 Support launch by using named pipe
  README.md
  server/src/main/java/com/microsoft/java/bs/core/Launcher.java
  server/src/main/java/com/microsoft/java/bs/core/internal/transport/NamedPipeStream.java
Labels: enhancement
